#!/usr/bin/env python3
"""Generate docs/FIELD_REFERENCE.md directly from uia_protocol_kernel.py's own
ENUMS/LANES/*_REQUIRED constants — never hand-maintained, so it cannot drift from
what validate() actually enforces. Run this after any change to those constants:

    python3 tools/generate_field_reference.py

2026-08-01: written after a 5-domain real-usage simulation found that the only
schema reference available was the kernel source itself, raising onboarding cost
for anyone constructing a checkpoint by hand for the first time.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import uia_protocol_kernel as k  # noqa: E402

OUT_PATH = Path(__file__).resolve().parent.parent / "docs" / "FIELD_REFERENCE.md"

TOP_LEVEL_ALWAYS_REQUIRED = [
    ("run_control", "how this run should continue — STOP_AT_HYPOTHESIS or RUN_FULL"),
    ("two_question_intake", "the two-question intake (issue statement + proposal question)"),
    ("emergency_containment", "emergency-bypass status; NOT_TRIGGERED for a normal run"),
    ("proposal_input", "how a user's proposal (if any) entered the run"),
    ("agency", "who is accountable/affected/decision-owning/etc. for this issue"),
    ("causal_analysis", "candidate mechanisms and the alternatives considered"),
    ("hypothesis_evidence_challenge", "the evidence ledger challenging each hypothesis"),
    ("hypothesis_portfolio", "the certified hypothesis cards (phase 12 checkpoint)"),
]

TOP_LEVEL_ONLY_FOR_RUN_FULL = [
    ("candidate_portfolio", "generated only if continuation_policy=RUN_FULL (past phase 12)"),
    ("intervention", "generated only if continuation_policy=RUN_FULL"),
    ("checker", "generated only if continuation_policy=RUN_FULL"),
    ("final", "generated only if continuation_policy=RUN_FULL"),
]


def render_set(items) -> str:
    return "\n".join(f"- `{v}`" for v in sorted(items))


def main() -> None:
    lines: list[str] = []
    lines.append("# UIA run-record field reference")
    lines.append("")
    lines.append(
        "**Generated by `tools/generate_field_reference.py` from "
        f"`uia_protocol_kernel.py` (protocol version `{k.VERSION}`) — do not hand-edit, "
        "re-run the generator instead.**"
    )
    lines.append("")
    lines.append(
        "This documents the schema `validate()` actually enforces, for constructing "
        "a run record for a NEW real issue (not the booking-app "
        "`--print-checkpoint-demo` fixture, and not the `--print-checkpoint-demo-2` "
        "second-domain fixture — both are starting templates, not the only shape "
        "the schema accepts)."
    )
    lines.append("")
    lines.append("## A note on \"local\"")
    lines.append("")
    lines.append(
        "`hypothesis_evidence_challenge.hypotheses[*].local_context_track` and "
        "`hypothesis_evidence_challenge.target_context` are about the **actual "
        "locale where the issue occurs / where its stakeholders are** — whatever "
        "country, region, or context that really is for your issue. Nothing in the "
        "schema requires Thai language or Thailand specifically; the built-in demo "
        "fixture just happens to use Thailand as its example locale "
        "(`target_context.country: \"Thailand\"`). Set `target_context.country` and "
        "`languages` to whatever is real for your issue."
    )
    lines.append("")
    lines.append("## Top-level objects")
    lines.append("")
    lines.append("Required for any checkpoint (including `STOP_AT_HYPOTHESIS`):")
    lines.append("")
    for name, note in TOP_LEVEL_ALWAYS_REQUIRED:
        lines.append(f"- `{name}` — {note}")
    lines.append("")
    lines.append("Only required if `run_control.continuation_policy == \"RUN_FULL\"` (past phase 12):")
    lines.append("")
    for name, note in TOP_LEVEL_ONLY_FOR_RUN_FULL:
        lines.append(f"- `{name}` — {note}")
    lines.append("")

    lines.append("## `run_control.continuation_policy`")
    lines.append("")
    lines.append(render_set(k.ENUMS["continuation_policy"]))
    lines.append("")

    lines.append("## `hypothesis_portfolio.hypothesis_cards[*].lane`")
    lines.append("")
    lines.append(
        "A `VALID_CHECKPOINT` needs at least 3 hypothesis cards spanning **all three** "
        "of these lanes (one independent, falsifiable explanation per lane):"
    )
    lines.append("")
    lines.append(render_set(k.LANES))
    lines.append("")

    lines.append("## `hypothesis_portfolio.hypothesis_cards[*]` required fields")
    lines.append("")
    lines.append(render_set(k.HYPOTHESIS_REQUIRED))
    lines.append("")
    lines.append(
        "**Exception (2026-08-01):** `authority_assumptions` may be an empty list "
        "if — and only if — the same card has `legal_relevance: \"NONE\"` AND "
        "`legal_status: \"NOT_REQUIRED\"`, i.e. this specific hypothesis genuinely "
        "has no authority/legal dimension (e.g. a purely mechanical or "
        "signal-processing hypothesis). Any other combination still requires a "
        "real, non-empty `authority_assumptions` list."
    )
    lines.append("")

    lines.append("## `hypothesis_portfolio.hypothesis_cards[*].representation_status` required fields")
    lines.append("")
    lines.append(render_set(k.REPRESENTATION_REQUIRED))
    lines.append("")

    lines.append("## `hypothesis_evidence_challenge.review_mode`")
    lines.append("")
    lines.append(
        "Free-text (not enum-constrained) with one recognized special value:"
    )
    lines.append("")
    lines.append(
        "- `\"TARGETED_SEARCH\"` (or any other value) — each hypothesis's "
        "`citation_cards[*]` must carry the full literature-citation field set: "
        "`authors_or_issuer`, `year`, `source_type`, `journal_or_repository`, "
        "`persistent_id_or_official_url`, plus the fields shared with "
        "`INTERNAL_DATA_AUDIT` below. This is the original schema shape."
    )
    lines.append(
        "- `\"INTERNAL_DATA_AUDIT\"` (2026-08-01) — for issues whose real evidence "
        "base is internal operational data (logs, tickets, sensor exports) rather "
        "than published literature. `citation_cards[*]` instead carry "
        "`source_system`, `query_or_filter`, `record_id_or_url` in place of the "
        "literature fields — everything else (falsifier, `source_classes_searched` "
        "length >= 2, `result_status`, `citation_audit == \"PASS\"`, the "
        "`global_certainty`/`local_applicability`/`evidence_balance`/"
        "`transfer_status` enums) is unchanged; this mode does not relax rigor, "
        "only the vocabulary of what counts as a citable source."
    )
    lines.append("")
    lines.append("`citation_cards[*]` fields shared by both modes:")
    lines.append("")
    lines.append(
        render_set(
            {
                "citation_id",
                "title",
                "context_country_or_region",
                "claim_supported_or_challenged",
                "direction",
                "quality",
                "directness",
                "context_fit",
                "metadata_verification",
                "scope_verification",
                "retrieved_at",
            }
        )
    )
    lines.append("")

    lines.append("## Other enums (`ENUMS` in `uia_protocol_kernel.py`)")
    lines.append("")
    for name in sorted(k.ENUMS):
        if name == "continuation_policy":
            continue  # already covered above
        lines.append(f"### `{name}`")
        lines.append("")
        lines.append(render_set(k.ENUMS[name]))
        lines.append("")

    lines.append("## `emergency_containment` required fields (when status != NOT_TRIGGERED)")
    lines.append("")
    lines.append(render_set(k.EMERGENCY_REQUIRED))
    lines.append("")

    lines.append("## `candidate_portfolio.candidates[*]` required fields (RUN_FULL only)")
    lines.append("")
    lines.append(render_set(k.CANDIDATE_REQUIRED))
    lines.append("")

    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
